### ISSUE TITLE
Indicate errors also in the section headers

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/properties-panel#180]
__Is your feature request related to a problem? Please describe__

With our approach to end-to-end validation, we try to hint users to problems in the model in any potential place, so the user won't miss any problem. We list all problems in the problems panel and highlight all fields in the properties panel with erroneous content. However, if you collapse a section in the properties panel, you won't see that there is a problem in any field inside this section. Additionally, problems related to whole sections (such as using extension properties prior to 8.1) can not be displayed properly, resulting in redundant highlighting on a per-item basis (see https://github.com/camunda/linting/pull/14). 

__Describe the solution you'd like__

In case there is any problem with any field inside a properties panel section, the "change" (respectively count) indicator should turn into an error sign, indicating that there is a problem to be fixed. In case the problem is with the whole section (such as with the extension properties example), an optional error message should be shown in the section header.

![Bildschirmfoto 2022-09-05 um 20 52 01](https://user-images.githubusercontent.com/56470362/188502326-49f86d2b-ce84-4996-b31a-51c946c6bc34.png)

![Bildschirmfoto 2022-09-05 um 20 53 33](https://user-images.githubusercontent.com/56470362/188502452-4b47d8bd-aa31-473f-84b7-8d4f3c045c03.png)

![Bildschirmfoto 2022-09-05 um 21 06 07](https://user-images.githubusercontent.com/56470362/188503434-6bb526f3-af12-4ac7-84a6-857a9ff98506.png)

__Describe alternatives you've considered__

__Additional context__

**Comment by christian-konrad** [comment]
@philippfromme please tell me if this is the right repo for this (or bpmn-js-properties-panel or even another one?)

**Comment by philippfromme** [comment]
We'll have to figure out how and where exactly to implement this, but this is the right place for the issue. 👍🏻

**Comment by smbea** [comment]
This has been [brought up again in slack](https://camunda.slack.com/archives/CKGH9LR40/p1688717337200019), in the context of confusing participants of a workshop. Moving to ready to we can discuss it next planning.

I had done some exploration of this issue: [see slack thread](https://camunda.slack.com/archives/GP70M0J6M/p1674225906939569) and [wip branch](https://github.com/bpmn-io/properties-panel/tree/add-error-icon-to-header) but didn't continue with it.

**Comment by smbea** [comment]
@marstamm will look into how much effort this will take and evaluate

**Comment by marstamm** [comment]
## Evaluation

This Issue opens 2 separate feature requests.
- 1️⃣  Show error state in the collapsed state
- 2️⃣  allow group linting (e.g. a message for the group instead of items)

In my opinion, 1️⃣  has the biggest impact as shown by the feedback received in slack. Given our existing infrastructure, this is actually low-hanging fruit as long as we only consider the Global error state.

A Group has access to the list of entries including their IDs. The `ErrorsContext` contains the list of global errors maintained by linting by entryId.
Using both, we can identify if the group contains an erroneous entry and act accordingly, e.g. by changing the color of the indicator:

![Recording 2023-07-12 at 11 30 33](https://github.com/bpmn-io/properties-panel/assets/21984219/eb0c0c4a-52b7-4e1a-b6ad-1a56b9a0e435)

Note that we do not consider local error state, so a duplicate ID would not be shown as an error, but also not committed to the XML:
![Recording 2023-07-12 at 11 35 23](https://github.com/bpmn-io/properties-panel/assets/21984219/200357fc-0060-4106-bf5a-85179646ef15)


---

For 2️⃣, we would need to create more infrastructure + lint rules to support error messages for groups. We also did not receive any direct feedback regarding this, so I propose to split the issues and tackle group-errors at a later point.

**Comment by philippfromme** [comment]
1️⃣ was the idea I had in mind. Integrates nicely with the way we're already doing things and 2️⃣ could still be built on top.
